version: '3.4'
services:
  db:
    image: mongo:4.2-bionic
    restart: always
    volumes:
      - ./rootfs/${ARCH}/data/db:/data/db
    ports:
      - "8081:8081"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456789
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: /app/beego
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

